### ISSUE TITLE
Write up tutorial!

### ISSUE THREAD

**Issue by vsoch** [fbartusch/snakemake_tutorial#2]
hey @fbartusch ! Did you want to give a first shot at writing up the tutorial? I just wrote one for carrierseq that uses the new Scientific Filesystem --> https://sci-f.github.io/apps/examples/carrierseq.scif and I thought it would be fun to do one akin to it. I'm not familiar with snakemake so I would need your help with that for sure.

**Comment by vsoch** [comment]
okay I got us started :)  https://github.com/sci-f/apps/blob/master/_posts/examples/2018-01-30-snakemake.scif.md

Rendered here!

https://sci-f.github.io/apps/examples/snakemake.scif

Take it away!! :D

**Comment by vsoch** [comment]
hey is this you? https://twitter.com/Fex013 I'm going to tweet it so others can give feedback and learn, and I want to make sure to add you (if you are on twitter).

**Comment by fbartusch** [comment]
Yeah, that's me.  But I'm not so active on Twitter.

**Comment by vsoch** [comment]
Thanks @fbartusch ! We have resolved this "issue" :)
