### ISSUE TITLE
question about environment.yaml

### ISSUE THREAD

**Issue by vsoch** [fbartusch/snakemake_tutorial#3]
hey @fbartusch ! I noticed this empty file `environment.yaml` in the repos and I don't see them being used anywhere. Is it needed for snakemake or can I delete?

**Comment by fbartusch** [comment]
Hey, you can delete it. I created it because it was mentioned somewhere in the Snakemake tutorial but I didn't use it in the end.

**Comment by vsoch** [comment]
okay cool! I will in the next push, I'm writing the script to run the different container snakemake pipelines and will add it to that. Thank you!
